baseURL = 'https://vaproh.space/'
languageCode = 'en-US'
title = 'vaproh'
theme = 'vaproh-theme'
enableRobotsTXT = true

[params]
  description = "Utkarsh's little corner of the internet."
  author = "Utkarsh"
  images = ["/img/og.png"]

[permalinks]
  archive = "/:title/"

[markup.goldmark.renderer]
  unsafe = true

[markup.highlight]
  noClasses = false
